- name: Install aptitude 
  apt:
    name: aptitude
    state: latest
    update_cache: yes
  become: yes   
  ## https://github.com/seemoo-lab/nexmon/issues/75
  #  - name: Actualiza cache, packages, y autoremuove
  #apt:
  #upgrade: dist 
  #update_cache: yes
  # autoremove not available in 16.04's ansible
  #autoremove: yes
  #become: yes
- name: Install packages requeridos from esta receta
  apt: 
    name: "{{ item }}"
    state: present
  with_items:
    - raspberrypi-kernel-headers
    - git
    - libgmp3-dev
    - gawk
    - qpdf
    - bison
    - flex
    - bc
    - libncurses5-dev
    - tcpdump
    - make
  become: yes
- name: Install rpi-source, utilitario from fuente de kernel en las Pi
  get_url: 
    url: https://raw.githubusercontent.com/notro/rpi-source/master/rpi-source
    dest: /usr/bin/rpi-source
    mode: 0755
    owner: root
    group: root
  become: yes
- name: execute rpi-source, from descargar fuente de kernel en las Pi
  command: rpi-source -d /usr/src/
  become: yes
  ignore_errors: true
- name: Descarga software nexmon
  git:
    #dest: "{{ ansible_user }}/nexmon" ## Pulga, sale como /home/pi/pi/nexmon...
    dest: /home/pi/nexmon
    repo: https://github.com/seemoo-lab/nexmon.git
  ignore_errors: true
- name: Parcha la herramienta nexutil, https://github.com/seemoo-lab/nexmon/issues/62
  lineinfile: >
    path=/home/pi/nexmon/utilities/nexutil/nexutil.c
    regexp='stdint'
    insertbefore='#define _XOPEN_SOURCE 700'
    line="#include <sys/types.h>
      #include <stdint.h>
      #include <stdlib.h>"
- name: configure lib isl
  copy:
    src: templates/libisl.so.10.0.0
    dest: /usr/local/lib/
  become: yes
- name: Compile nexmon
  command: ln -s /usr/local/lib/libisl.so.10.0.0 /usr/local/lib/libisl.so
  become: yes
- name: Compile nexmon
  command: ln -s /usr/local/lib/libisl.so /usr/lib/arm-linux-gnueabihf/libisl.so.10
  become: yes
- name: compile lib isl
  command: make
  args:
    chdir: /home/pi/nexmon/buildtools/isl-0.10
  become: yes

- name: install lib isl
  command: make
  args:
    chdir: /home/pi/nexmon/buildtools/isl-0.10
  become: yes

- name: Compile nexmon
  command: make
  args:
    chdir: /home/pi/nexmon

- name: Compile software nexmon, bcm43430a1 chipset
  command: make 
  args:
    chdir: /home/pi/nexmon/patches/bcm43430a1/7_45_41_46/nexmon/
  become: yes
- name: Realiza respaldo de firmware, bcm43430a1 chipset
  command: make backup-firmware
  args:
    chdir: /home/pi/nexmon/patches/bcm43430a1/7_45_41_46/nexmon/
  become: yes
- name: Instlla nuevo firmware, bcm43430a1 chipset
  command: make install-firmware
  args:
    chdir: /home/pi/nexmon/patches/bcm43430a1/7_45_41_46/nexmon/
  become: yes
- name: Compile utilizalities nextutil from software nexmon
  command: make 
  args:
    chdir: /home/pi/nexmon/utilities/nexutil
  become: yes
- name: Install utililitiesio nextutil from software nexmon
  command: make install
  args:
    chdir: /home/pi/nexmon/utilities/nexutil
  become: yes
- name: Remuove packages
  apt:
    name: "{{ item }}"
    state: absent
  become: yes
  with_items:
    - wpasupplicant
- name: Decide si debe copiar nuevo módulo de kernel
  command: test "md5sum /lib/modules/4.14.77-v7+/kernel/drivers/net/wireless/brcm80211/brcmfmac/brcmfmac.ko" == "52623c3a481dca9a233088deab271f79"
  register: modulo_viejo
  ignore_errors: true
- name: COpy file
  file:
    src: /home/pi/nexmon/patches/bcm43430a1/7_45_41_46/nexmon/brcmfmac_4.14.y-nexmon/brcmfmac.ko
    dest: /lib/modules/4.14.77-v7+/kernel/drivers/net/wireless/broadcom/brcm80211/brcmfmac/brcmfmac.ko
    owner: root
    group: root
    mode: 0644
  become: yes
  when: modulo_viejo.changed
- name: execute depmod
  command: depmod -a
  become: yes
  when: modulo_viejo.changed
